export const SPECIALTIES = [
  "General Physician",
  "Cardiologist",
  "Dermatologist",
  "Pediatrician",
  "Psychiatrist",
  "Psychologist",
  "Orthopedic Surgeon",
  "Neurologist",
  "Oncologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Endocrinologist",
  "Nephrologist",
  "Rheumatologist",
  "Ophthalmologist",
  "ENT Specialist",
  "Urologist",
  "Gynecologist",
  "Obstetrician",
  "Radiologist",
  "Pathologist",
  "Geriatrician",
  "Sports Medicine",
  "Allergist",
  "Immunologist",
  "Hepatologist",
  "Hematologist",
  "Plastic Surgeon",
  "Cardiothoracic Surgeon",
  "Neurosurgeon",
  "Vascular Surgeon",
  "Trauma Surgeon",
  "Andrologist",
  "Ayurveda Physician",
  "Homeopathy Doctor",
  "Dentist",
  "Oral Surgeon",
  "Physiotherapist",
  "Dietitian",
  "Nutritionist",
  "Sleep Medicine",
  "Pain Management",
  "Palliative Care",
  "Reproductive Medicine",
  "Sexologist",
];
